name: fund_bridge
description: "Funding application to connect donors with people in need."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  country_flags: ^4.1.0
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  google_nav_bar: ^5.0.7
  sqflite: ^2.4.1
  path: ^1.9.1
  path_provider: ^2.1.5
  flutter_secure_storage: ^10.0.0
  flutter_native_splash: ^2.4.4
  image_picker: ^1.2.1
  location: ^6.0.2

flutter_native_splash:
  color: "#ffffff"
  image: imgs/logo.png
  android: true
  ios: true
  web: false

  android_12:
    image: imgs/logo.png
    color: "#ffffff"

  fullscreen: true
  android_gravity: center
  ios_content_mode: center

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "imgs/logo.png"
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - imgs/Frame.jpg
    - imgs/Frame.png
    - imgs/hug.png
    - imgs/charity.png
    - imgs/logo.png
    - imgs/screenshot.png
    - imgs/profile.png
    - imgs/rural_areas.jpg
    - imgs/img.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Medium.ttf
